#!/bin/bash
set -eo pipefail

# Builds Docker image of Community App application.
# This script expects a single argument: NODE_CONFIG_ENV, which must be either
# "development" or "production".

NODE_CONFIG_ENV=$1

# Selects proper AWS_ACCOUNT_ID / AWS_REGION for dev / prod builds. Fails
# execution, if NODE_CONFIG_ENV argument is missing or incorrect.
if [ $NODE_CONFIG_ENV == production ]
then
  AWS_ACCOUNT_ID=$PROD_AWS_ACCOUNT_ID
  AWS_REGION=$PROD_AWS_REGION
  CDN_URL=$PROD_CDN_URL
  SERVER_API_KEY=$PROD_SERVER_API_KEY
  FILESTACK_API_KEY=$PROD_FILESTACK_API_KEY
  FILESTACK_SUBMISSION_CONTAINER=$PROD_FILESTACK_SUBMISSION_CONTAINER
  SEGMENT_IO_API_KEY=$PROD_SEGMENT_IO_API_KEY
  AWS_ECS_CLUSTER=$PROD_AWS_ECS_CLUSTER
  AUTH0_CLIENT_ID=$PROD_AUTH0_CLIENT_ID

  TC_M2M_CLIENT_ID=$PROD_TC_M2M_CLIENT_ID
  TC_M2M_CLIENT_SECRET=$PROD_TC_M2M_CLIENT_SECRET
  TC_M2M_AUDIENCE=$PROD_TC_M2M_AUDIENCE
  TC_M2M_GRANT_TYPE=$PROD_TC_M2M_GRANT_TYPE

elif [ $NODE_CONFIG_ENV == development ]
then
  AWS_ACCOUNT_ID=$DEV_AWS_ACCOUNT_ID
  AWS_REGION=$DEV_AWS_REGION
  CDN_URL=$DEV_CDN_URL
  SERVER_API_KEY=$DEV_SERVER_API_KEY
  FILESTACK_API_KEY=$DEV_FILESTACK_API_KEY
  FILESTACK_SUBMISSION_CONTAINER=$DEV_FILESTACK_SUBMISSION_CONTAINER
  SEGMENT_IO_API_KEY=$DEV_SEGMENT_IO_API_KEY
  AWS_ECS_CLUSTER=$DEV_AWS_ECS_CLUSTER

  TC_M2M_CLIENT_ID=$DEV_TC_M2M_CLIENT_ID
  TC_M2M_CLIENT_SECRET=$DEV_TC_M2M_CLIENT_SECRET
  TC_M2M_AUDIENCE=$DEV_TC_M2M_AUDIENCE
  TC_M2M_GRANT_TYPE=$DEV_TC_M2M_GRANT_TYPE

elif [ $NODE_CONFIG_ENV == test ]
then
  AWS_ACCOUNT_ID=$TEST_AWS_ACCOUNT_ID
  AWS_REGION=$TEST_AWS_REGION
  CDN_URL=$TEST_CDN_URL
  SERVER_API_KEY=$TEST_SERVER_API_KEY
  FILESTACK_API_KEY=$TEST_FILESTACK_API_KEY
  FILESTACK_SUBMISSION_CONTAINER=$TEST_FILESTACK_SUBMISSION_CONTAINER
  SEGMENT_IO_API_KEY=$TEST_SEGMENT_IO_API_KEY
  AWS_ECS_CLUSTER=$TEST_AWS_ECS_CLUSTER
  AUTH0_CLIENT_ID=$DEV_AUTH0_CLIENT_ID

  TC_M2M_CLIENT_ID=$DEV_TC_M2M_CLIENT_ID
  TC_M2M_CLIENT_SECRET=$DEV_TC_M2M_CLIENT_SECRET
  TC_M2M_AUDIENCE=$DEV_TC_M2M_AUDIENCE
  TC_M2M_GRANT_TYPE=$DEV_TC_M2M_GRANT_TYPE
elif [ $NODE_CONFIG_ENV == production_beta ]
then
  AWS_ACCOUNT_ID=$PRODBETA_AWS_ACCOUNT_ID
  AWS_REGION=$PRODBETA_AWS_REGION
  CDN_URL=$PRODBETA_CDN_URL
  SERVER_API_KEY=$PRODBETA_SERVER_API_KEY
  FILESTACK_API_KEY=$PRODBETA_FILESTACK_API_KEY
  FILESTACK_SUBMISSION_CONTAINER=$PRODBETA_FILESTACK_SUBMISSION_CONTAINER
  SEGMENT_IO_API_KEY=$PRODBETA_SEGMENT_IO_API_KEY
  AWS_ECS_CLUSTER=$PRODBETA_AWS_ECS_CLUSTER
  AUTH0_CLIENT_ID=$PRODBETA_AUTH0_CLIENT_ID

  TC_M2M_CLIENT_ID=$PRODBETA_TC_M2M_CLIENT_ID
  TC_M2M_CLIENT_SECRET=$PRODBETA__TC_M2M_CLIENT_SECRET
  TC_M2M_AUDIENCE=$PRODBETA__TC_M2M_AUDIENCE
  TC_M2M_GRANT_TYPE=$PRODBETA__TC_M2M_GRANT_TYPE
else
  exit 1
fi

# Builds Docker image of the app.
TAG=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_ECS_CLUSTER:$CIRCLE_SHA1
docker build -t $TAG \
  --build-arg AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID \
  --build-arg CDN_URL=$CDN_URL \
  --build-arg COGNITIVE_NEWSLETTER_SIGNUP_APIKEY=$COGNITIVE_NEWSLETTER_SIGNUP_APIKEY \
  --build-arg COGNITIVE_NEWSLETTER_SIGNUP_URL=$COGNITIVE_NEWSLETTER_SIGNUP_URL \
  --build-arg CONTENTFUL_CDN_API_KEY=$CONTENTFUL_CDN_API_KEY \
  --build-arg CONTENTFUL_PREVIEW_API_KEY=$CONTENTFUL_PREVIEW_API_KEY \
  --build-arg CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID \
  --build-arg CONTENTFUL_ZURICH_SPACE_ID=$CONTENTFUL_ZURICH_SPACE_ID \
  --build-arg CONTENTFUL_ZURICH_CDN_API_KEY=$CONTENTFUL_ZURICH_CDN_API_KEY \
  --build-arg CONTENTFUL_ZURICH_PREVIEW_API_KEY=$CONTENTFUL_ZURICH_PREVIEW_API_KEY \
  --build-arg CONTENTFUL_TOPGEAR_CDN_API_KEY=$CONTENTFUL_TOPGEAR_CDN_API_KEY \
  --build-arg CONTENTFUL_TOPGEAR_PREVIEW_API_KEY=$CONTENTFUL_TOPGEAR_PREVIEW_API_KEY \
  --build-arg CONTENTFUL_TOPGEAR_SPACE_ID=$CONTENTFUL_TOPGEAR_SPACE_ID \
  --build-arg FILESTACK_API_KEY=$FILESTACK_API_KEY \
  --build-arg FILESTACK_SUBMISSION_CONTAINER=$FILESTACK_SUBMISSION_CONTAINER \
  --build-arg MAILCHIMP_API_KEY=$MAILCHIMP_API_KEY \
  --build-arg MAILCHIMP_BASE_URL=$MAILCHIMP_BASE_URL \
  --build-arg NODE_CONFIG_ENV=$NODE_CONFIG_ENV \
  --build-arg OPEN_EXCHANGE_RATES_KEY=$OPEN_EXCHANGE_RATES_KEY \
  --build-arg SEGMENT_IO_API_KEY=$SEGMENT_IO_API_KEY \
  --build-arg SERVER_API_KEY=$SERVER_API_KEY \
  --build-arg TC_M2M_CLIENT_ID=$TC_M2M_CLIENT_ID \
  --build-arg TC_M2M_CLIENT_SECRET=$TC_M2M_CLIENT_SECRET \
  --build-arg TC_M2M_AUDIENCE=$TC_M2M_AUDIENCE \
  --build-arg TC_M2M_GRANT_TYPE=$TC_M2M_GRANT_TYPE .

# Copies "node_modules" from the created image, if necessary for caching.
docker create --name app $TAG

if [ -d node_modules ]
then
  # If "node_modules" directory already exists, we should compare
  # "package-lock.json" from the code and from the container to decide,
  # whether we need to re-cache, and thus to copy "node_modules" from
  # the Docker container.
  mv package-lock.json old-package-lock.json
  docker cp app:/opt/app/package-lock.json package-lock.json
  set +eo pipefail
  UPDATE_CACHE=$(cmp package-lock.json old-package-lock.json)
  set -eo pipefail
else
  # If "node_modules" does not exist, then cache must be created.
  UPDATE_CACHE=1
fi

if [ "$UPDATE_CACHE" == 1 ]
then
  docker cp app:/opt/app/node_modules .
fi